// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsrmueavzxvxkqvtrxcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzcm11ZWF2enh2eGtxdnRyeGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Nzg1ODIsImV4cCI6MjA3MzQ1NDU4Mn0.OLjAJ8Zji08uNt5cKRNEl9GlesRdzOnruO9KARixUaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});